package parser

import "github.com/m4tthewde/gov1/internal"

type State struct {
	OperatingPointIdc    int
	seenFrameHeader      bool
	renderWidth          int
	renderHeight         int
	upscaledWidth        int
	upscaledHeight       int
	TileNum              int
	MiCols               int
	MiRows               int
	MiColStarts          []int
	MiRowStarts          []int
	MiCol                int
	MiRow                int
	MiSize               int
	MiSizes              [][]int
	MiRowStart           int
	MiColStart           int
	MiRowEnd             int
	MiColEnd             int
	TileColsLog2         int
	TileRowsLog2         int
	TileCols             int
	TileRows             int
	TileSizeBytes        int
	CurrentQIndex        int
	DeltaLF              []int
	RefLrWiener          [][][]int
	Num4x4BlocksWide     []int
	Num4x4BlocksHigh     []int
	ReadDeltas           bool
	Cdef                 internal.Cdef
	BlockDecoded         [][][]int
	FrameRestorationType []int
	LoopRestorationSize  []int
	AvailU               bool
	AvailL               bool
	AvailUChroma         bool
	AvailLChroma         bool
	FeatureEnabled       [][]int
	FeatureData          [][]int
	RefFrame             []int
	RefFrames            [][][]int
	RefFrameWidth        []int
	RefFrameHeight       []int
	GmType               []int
	PrevGmParams         [][]int
	PrevSegmentIds       [][]int
	CurrFrame            [][][]int
	SymbolMaxBits        int
}
