package shared

const BLOCK_INVALID = 3
const BLOCK_SIZES = 22
const BLOCK_4X4 = 0
const BLOCK_4X8 = 1
const BLOCK_8X4 = 2
const BLOCK_8X8 = 3
const BLOCK_8X16 = 4
const BLOCK_16X8 = 5
const BLOCK_16X16 = 6
const BLOCK_16X32 = 7
const BLOCK_32X16 = 8
const BLOCK_32X32 = 9
const BLOCK_32X64 = 10
const BLOCK_64X32 = 11
const BLOCK_64X64 = 12
const BLOCK_64X128 = 13
const BLOCK_128X64 = 14
const BLOCK_128X128 = 15
const BLOCK_4X16 = 16
const BLOCK_16X4 = 17
const BLOCK_8X32 = 18
const BLOCK_32X8 = 19
const BLOCK_16X64 = 20
const BLOCK_64X16 = 21

var Partition_Subsize = [][]int{
	{
		BLOCK_4X4,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_128X128,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X4,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_128X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_4X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X128,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_4X4,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X4,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_128X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X4,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_128X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_4X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X128,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_4X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X128,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X4,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_32X8,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_64X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
	{
		BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_4X16,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_8X32,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_16X64,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
		BLOCK_INVALID, BLOCK_INVALID, BLOCK_INVALID,
	},
}

var Subsampled_Size = [][][]int{
	{{BLOCK_4X4, BLOCK_4X4}, {BLOCK_4X4, BLOCK_4X4}},
	{{BLOCK_4X8, BLOCK_4X4}, {BLOCK_INVALID, BLOCK_4X4}},
	{{BLOCK_8X4, BLOCK_INVALID}, {BLOCK_4X4, BLOCK_4X4}},
	{{BLOCK_8X8, BLOCK_8X4}, {BLOCK_4X8, BLOCK_4X4}},
	{{BLOCK_8X16, BLOCK_8X8}, {BLOCK_INVALID, BLOCK_4X8}},
	{{BLOCK_16X8, BLOCK_INVALID}, {BLOCK_8X8, BLOCK_8X4}},
	{{BLOCK_16X16, BLOCK_16X8}, {BLOCK_8X16, BLOCK_8X8}},
	{{BLOCK_16X32, BLOCK_16X16}, {BLOCK_INVALID, BLOCK_8X16}},
	{{BLOCK_32X16, BLOCK_INVALID}, {BLOCK_16X16, BLOCK_16X8}},
	{{BLOCK_32X32, BLOCK_32X16}, {BLOCK_16X32, BLOCK_16X16}},
	{{BLOCK_32X64, BLOCK_32X32}, {BLOCK_INVALID, BLOCK_16X32}},
	{{BLOCK_64X32, BLOCK_INVALID}, {BLOCK_32X32, BLOCK_32X16}},
	{{BLOCK_64X64, BLOCK_64X32}, {BLOCK_32X64, BLOCK_32X32}},
	{{BLOCK_64X128, BLOCK_64X64}, {BLOCK_INVALID, BLOCK_32X64}},
	{{BLOCK_128X64, BLOCK_INVALID}, {BLOCK_64X64, BLOCK_64X32}},
	{{BLOCK_128X128, BLOCK_128X64}, {BLOCK_64X128, BLOCK_64X64}},
	{{BLOCK_4X16, BLOCK_4X8}, {BLOCK_INVALID, BLOCK_4X8}},
	{{BLOCK_16X4, BLOCK_INVALID}, {BLOCK_8X4, BLOCK_8X4}},
	{{BLOCK_8X32, BLOCK_8X16}, {BLOCK_INVALID, BLOCK_4X16}},
	{{BLOCK_32X8, BLOCK_INVALID}, {BLOCK_16X8, BLOCK_16X4}},
	{{BLOCK_16X64, BLOCK_16X32}, {BLOCK_INVALID, BLOCK_8X32}},
	{{BLOCK_64X16, BLOCK_INVALID}, {BLOCK_32X16, BLOCK_32X8}},
}

const LAST_FRAME = 1
const LAST2_FRAME = 2
const LAST3_FRAME = 3
const GOLDEN_FRAME = 4
const BWDREF_FRAME = 5
const ALTREF2_FRAME = 6
const ALTREF_FRAME = 7

const NEARESTMV = 14
const NEARMV = 15
const GLOBALMV = 16
const NEWMV = 17
const NEAREST_NEARESTMV = 18
const NEAR_NEARMV = 19
const NEAREST_NEWMV = 20
const NEW_NEARESTMV = 21
const NEAR_NEWMV = 22
const NEW_NEARMV = 23
const GLOBAL_GLOBALMV = 24
const NEW_NEWMV = 25

const SUPERRES_NUM = 8

const TX_MODE_LARGEST = 1
const TX_MODE_SELECT = 2
